version: '3.8'

services:

  postgresql:
    container_name: grpccrud
    image: postgres:12.1
    restart: always
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    volumes:
      - ./tools/docker/postgres/initdb:/docker-entrypoint-initdb.d postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: grpc_crud
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.30
    volumes: 
      - yumzy-pgadmin-default:/var/lib/pgadin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - 8081:80

volumes:
  yumzy-pgadmin-default:
    driver: local
